apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignmenttesting-deployment
  labels:
    app: assignmenttesting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignmenttesting
  template:
    metadata:
      labels:
        app: assignmenttesting
    spec:
      containers:
      - name: maventest-container
        image: vaishnaveeshree03/assignmenttesting:latest
        ports:
        - containerPort: 8080
