apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignmenttesting-deployment
spec:
  replicas: 1  # Number of replicas (Pods) to run
  selector:
    matchLabels:
      app: assignmenttesting
  template:
    metadata:
      labels:
        app: assignmenttesting
    spec:
      containers:
        - name: assignmenttesting
          image: vaishnaveeshree03/assignmenttesting:latest
          ports:
            - containerPort: 8080
